// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlCm5JeqI_UuLD5hCSk8uxcNSiEFS6rvA',
    appId: '1:575665171897:web:ddf1a8de27af6e67499a68',
    messagingSenderId: '575665171897',
    projectId: 'multicount-47aa9',
    authDomain: 'multicount-47aa9.firebaseapp.com',
    storageBucket: 'multicount-47aa9.firebasestorage.app',
    measurementId: 'G-ZJM4LJKZYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs-4y7mp4sKTyulj0GrwaoMZBjROWHGgU',
    appId: '1:575665171897:android:17c5828b428c84a3499a68',
    messagingSenderId: '575665171897',
    projectId: 'multicount-47aa9',
    storageBucket: 'multicount-47aa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIcIJcoPavhDK6MlNTAs4A-26NnMZF314',
    appId: '1:575665171897:ios:436e9ec4f04e1035499a68',
    messagingSenderId: '575665171897',
    projectId: 'multicount-47aa9',
    storageBucket: 'multicount-47aa9.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );
}
