import 'package:cloud_firestore/cloud_firestore.dart';

class CollectionManager {
  final FirebaseFirestore db;
  final String collectionName;

  CollectionManager({
    required this.db,
    required this.collectionName,
  });

  /// Create - Add new document with either manual/auto generated ID [C]
  Future<void> addNewDocument({String? documentId, required Map<String, dynamic> documentMap}) async {
    try {
      DocumentReference docRef;
      if(documentId!=null){
        await db.collection(collectionName).doc(documentId).set(documentMap);
        print('✅ Document added successfully with manual ID: $documentId');
      }else{
        docRef = await db.collection(collectionName).add(documentMap);
        print('✅ Document added successfully with autoGenerated ID: ${docRef.id}');
      }
    } catch (e) {
      print('❌ Failed to add document: $e');
    }
  }


  /// <<<<<<<<<<<<<<<<< READ >>>>>>>>>>>>>>>>>
  /// Read - Retrieve all documents in the collection [R], Future enhance: Read the documents IDs not only their values
  Future<List<Map<String,dynamic>>> readCollection() async {
    List<Map<String,dynamic>> documents = [];
    try {
      final snapshot = await db.collection(collectionName).get();
      for (var doc in snapshot.docs) {
        documents.add(doc.data());
      }
      return documents;
    } catch (e) {
      print('❌ Failed to read collection: $e');
      return [];
    }
  }

  /// Read - Retrieve specific document in the collection [R]
  Future<Map<String,dynamic>> readDocument(String documentId) async {
    Map<String,dynamic>? document = {};
    try {
      final snapshot = await db.collection(collectionName).doc(documentId).get();
      document = snapshot.data();
      return document ?? {};
    } catch (e) {
      print('❌ Failed to read collection: $e');
      return {};
    }
  }

  /// Read- listen to specific document in the collection [R]
  void subscribeToDocument({required String documentId,String? desiredKey}) {
    db.collection(collectionName).doc(documentId).snapshots().listen((DocumentSnapshot snapshot) {
      if (snapshot.exists) {
        /// TODO: the logic we want
        Map<String,dynamic> updatedDocument = snapshot.data() as Map<String,dynamic>;
        if(desiredKey!=null){
          print('Document data: ${updatedDocument[desiredKey]}');
        }else{
          print('Document data: $updatedDocument');
        }
      } else {
        print('Document does not exist');
      }
    }).onError((error) => print('Error listening to document: $error'));
  }

  /// <<<<<<<<<<<<<<<<< READ >>>>>>>>>>>>>>>>>


  /// Update - Update a specific document by ID [U]
  Future<void> updateDocument({
    required String documentId,
    required Map<String, dynamic> documentNewMap,
  }) async {
    try {
      await db.collection(collectionName).doc(documentId).update(documentNewMap);
      print('✅ Document $documentId updated successfully.');
    } catch (e) {
      print('❌ Failed to update document: $e');
    }
  }


  /// Delete - Delete a specific document by ID [D]
  Future<void> deleteDocument({
    required String documentId,
  }) async {
    try {
      await db.collection(collectionName).doc(documentId).delete();
      print('🗑️ Document $documentId deleted successfully.');
    } catch (e) {
      print('❌ Failed to delete document: $e');
    }
  }
}